### ISSUE TITLE
Cannot read property 'longitude' of undefined

### ISSUE THREAD

**Issue by abalad** [manuelbieh/Geolib#130]
This error is always generated when passing an Array Object. I think the problem is the interpretation of JavaScript [Array = Object]

```
TypeError: Cannot read property 'longitude' of undefined
    at Geolib.getLon (E:\Projetos\OtiSEG\EventValidator\node_modules\geolib\dist\geolib.js:160:115)
    at Geolib.longitude (E:\Projetos\OtiSEG\EventValidator\node_modules\geolib\dist\geolib.js:165:32)
    at Geolib.isPointInside (E:\Projetos\OtiSEG\EventValidator\node_modules\geolib\dist\geolib.js:634:31)
    at module.exports (E:\Projetos\OtiSEG\EventValidator\app\validators\cerca\polygon.js:14:12)
    at validate (E:\Projetos\OtiSEG\EventValidator\app\validators\cerca\index.js:10:25)
    at E:\Projetos\OtiSEG\EventValidator\app\validators\cerca\index.js:22:21
    at Array.forEach (native)
    at E:\Projetos\OtiSEG\EventValidator\app\validators\cerca\index.js:21:24
    at model.Query.<anonymous> (E:\Projetos\OtiSEG\EventValidator\node_modules\mongoose\lib\model.js:3433:16)
    at E:\Projetos\OtiSEG\EventValidator\node_modules\kareem\index.js:273:21
    at E:\Projetos\OtiSEG\EventValidator\node_modules\kareem\index.js:127:16
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

```
let myArray = [ { longitude: -53.837042, latitude: -24.276739 },
  { longitude: -53.833308, latitude: -24.2882 },
  { longitude: -53.844767, latitude: -24.291369 },
  { longitude: -53.848586, latitude: -24.27979 },
  { longitude: -53.837042, latitude: -24.276739 } ]

console.log(typeof myArray); // 'object'

geolib.isPointInside({longitude: rastreamento.longitude, latitude: rastreamento.latitude},
 myArray);
```
**It is the same behavior that is found here**: [Link](http://stackoverflow.com/questions/12996871/why-does-typeof-array-with-objects-return-object-and-not-array)

**Comment by geekzolanos** [comment]
Same bug here (Version 2.0.22)

ERROR TypeError: Cannot read property 'latitude' of undefined
    at Geolib.coords (geolib.js:179)
    at Geolib.getDistance (geolib.js:247)

**Comment by PanMan** [comment]
I have the same. The detection in ```getKeys``` seems off.
Fixed it by doing this:
```
dist: geolib.getDistance({latitude:obj1.latitude, longitude: obj1.longitude},{latitude:obj2.latitude, longitude: obj2.longitude})
```
But those objects should just work directly

**Comment by manuelbieh** [comment]
Should no longer happen in v3, which I will release shortly!
