### ISSUE TITLE
I am receiving this error since yesterday when i try to open the app on a mac

### ISSUE THREAD

**Issue by rbdemarch** [manuelbieh/geolib#267]
Uncaught Exception:
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Applications/Polkadot-JS Apps.app/Contents/Resources/app.asar/packages/apps-electron/build/electron.js
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:13)
at Module.load (internal/modules/cjs/loader.js:935:32)
at Module._load (internal/modules/cjs/loader.js:776:14)
at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
at Object.<anonymous> (electron/js2c/browser_init.js:197:3336)
at Object../lib/browser/init.ts (electron/js2c/browser_init.js:197:3540)
at __webpack_require__ (electron/js2c/browser_init.js:1:128)
at electron/js2c/browser_init.js:1:1200
at electron/js2c/browser_init.js:1:1267
at NativeModule.compileForInternalLoader (internal/bootstrap/loaders.js:283:7)

**Comment by manuelbieh** [comment]
Wrong repo
