### ISSUE TITLE
toString() error using Geolib

### ISSUE THREAD

**Issue by bomanimc** [manuelbieh/geolib#88]
Any call to a Geolib function returns this error using Chrome Version 51.0.2704.103 (64-bit).
<img width="533" alt="screen shot 2016-06-18 at 4 54 31 pm" src="https://cloud.githubusercontent.com/assets/6589909/16174415/db8bc8ba-3575-11e6-904c-6935fde62cf6.png">
<img width="541" alt="screen shot 2016-06-18 at 4 55 24 pm" src="https://cloud.githubusercontent.com/assets/6589909/16174416/db8ce394-3575-11e6-8642-cf7545ada39c.png">

gpsPoints is structure like so:
<img width="535" alt="screen shot 2016-06-18 at 4 59 10 pm" src="https://cloud.githubusercontent.com/assets/6589909/16174429/4f447662-3576-11e6-89f2-1fda356523f0.png">

Can you give insight into why this is happening?

**Comment by ngprnk** [comment]
class Distance {
  toRadians(degrees) {
    return degrees * (Math.PI / 180);
  }

  calc(from, to) {
    const lat1 = parseFloat(from.lat);
    const lon1 = parseFloat(from.lng);
    const lat2 = parseFloat(to.lat);
    const lon2 = parseFloat(to.lng);
    const R = 6371; // Radius of the earth in km
    const dLat = this.deg2rad(lat2 - lat1); // deg2rad below
    const dLon = this.deg2rad(lon2 - lon1);
    const a =
      Math.sin(dLat / 2) * Math.sin(dLat / 2) +
      Math.cos(this.deg2rad(lat1)) * Math.cos(this.deg2rad(lat2)) *
      Math.sin(dLon / 2) * Math.sin(dLon / 2);
    const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
    const d = R * c; // Distance in km
    return d;
  }

  deg2rad(deg) {
    return deg * (Math.PI / 180);
  }
}

export default new Distance();

**Comment by kerberjg** [comment]
Bump, this is still a relevant problem!

**Comment by loonycv** [comment]
any news?

**Comment by manuelbieh** [comment]
Can somebody please provide a minimal reproducible example? I don't really understand what's happening here.

**Comment by mateusppereira** [comment]
The prop name of your `gpsPoints` is `latitute`. Geolib expect this to be `latitude` or `lat`

**Comment by GuruKarmakar** [comment]
add this line inside  /node_modules/geolib/lib/index.js:1:1884
if(!n) return 1;
var n=t.toString().trim();

**Comment by hbarefootVPX** [comment]
Hi Guys, any update on this 

`TypeError: Cannot read property 'toString' of undefined
    at v (/Users/henrybarefoot/Documents/local-repos/MIXX/node_modules/geolib/lib/index.js:1:4333)
    at t (/Users/henrybarefoot/Documents/local-repos/MIXX/node_modules/geolib/lib/index.js:1:6670)
    at A (/Users/henrybarefoot/Documents/local-repos/MIXX/node_modules/geolib/lib/index.js:1:7055)
    at et (/Users/henrybarefoot/Documents/local-repos/MIXX/node_modules/geolib/lib/index.js:1:13125)
    at /Users/henrybarefoot/Documents/local-repos/MIXX/modules/stores.js:74:33
    at Array.map (<anonymous>)
    at Object.getClosestStores (/Users/henrybarefoot/Documents/local-repos/MIXX/modules/stores.js:67:16)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
TypeError: Cannot read property 'toString' of undefined
    at v (/Users/henrybarefoot/Documents/local-repos/MIXX/node_modules/geolib/lib/index.js:1:4333)
    at t (/Users/henrybarefoot/Documents/local-repos/MIXX/node_modules/geolib/lib/index.js:1:6670)
    at A (/Users/henrybarefoot/Documents/local-repos/MIXX/node_modules/geolib/lib/index.js:1:7055)
    at et (/Users/henrybarefoot/Documents/local-repos/MIXX/node_modules/geolib/lib/index.js:1:13125)
    at /Users/henrybarefoot/Documents/local-repos/MIXX/modules/stores.js:74:33
    at Array.map (<anonymous>)
    at Object.getClosestStores (/Users/henrybarefoot/Documents/local-repos/MIXX/modules/stores.js:67:16)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)`
